billproject/billproject/urls.py
from django.contrib import admin
from django.urls import path,include
from billproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('credentails.urls')),
      ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

billproject/credentails/urls.py
from django.urls import path,include

from . import views
app_name='credentails'
urlpatterns = [
    path('',views.sregister,name='sregister'),
    path('register/',views.searchindex,name='searchindex'),
    path('register/<int:reg_id>/',views.detail,name='registerdetail')


]

billproject/credentails/models.py
from django.db import models
from datetime import datetime
from dateutil.relativedelta import relativedelta

class Registers(models.Model):
    admn_no = models.IntegerField(default=0)
    sname = models.CharField(max_length=100)
    dob = models.DateField()
    aadharno = models.IntegerField(default=0)
    email_id = models.EmailField()
    phno = models.IntegerField(default=0)
    address = models.TextField()
    course = models.CharField(max_length=100)
    doj = models.DateField()
    duration = models.PositiveIntegerField(default=0)
    end_date = models.DateField(null=True, blank=True)
    mode_choices = [('online', 'Online'), ('offline', 'Offline'), ('recorded', 'Recorded'), ]
    mode = models.CharField(max_length=10, choices=mode_choices)
    course_fee = models.IntegerField(default=0)
    emi = models.IntegerField(default=0)
    permonth = models.IntegerField(null=True, blank=True)

def save(self, *args, **kwargs):
        doj = datetime.strptime(self.doj, '%Y-%m-%d').date()
        duration = self.duration

        end_date = doj + relativedelta(months=duration)
        self.end_date = end_date.strftime('%Y-%m-%d')
        super().save(*args, **kwargs)

def __str__(self):
        return f"Event {self.id}"


# Create your models here.

billproject/credentails/views.py
from django.shortcuts import render,redirect
from . models import Registers
from dateutil.relativedelta import relativedelta
from datetime import datetime, timedelta
from django.http import HttpResponse
def sregister(request):
    register=Registers.objects.all()
    if request.method == 'POST':

        admn_no = request.POST.get('admn_no')

        sname = request.POST.get('sname')

        dob = request.POST.get('dob')

        aadharno = request.POST.get('aadharno')
        email_id = request.POST.get('email_id')

        phno = request.POST.get('phno')

        address = request.POST.get('address')

        course = request.POST.get('course')
        doj = request.POST.get('doj')
        duration = int(request.POST.get('duration'))
        end_date = (datetime.strptime(doj, '%Y-%m-%d') + relativedelta(months=duration)).strftime('%Y-%m-%d')

        mode = request.POST.get('mode')

        course_fee = int(request.POST.get('course_fee'))

        emi = int(request.POST.get('emi'))
        permonth = course_fee / emi
        register=Registers(admn_no=admn_no,sname=sname,dob=dob,aadharno=aadharno,email_id=email_id,
                                phno=phno,address=address,course=course,doj=doj,duration=duration,
                                end_date=end_date,mode=mode,course_fee=course_fee,emi=emi,permonth=permonth)
        register.save()
        print("Data Saved")

    else:
        doj = ''
        duration = ''
        end_date = ''

    context = {
        'doj': doj,
        'duration': duration,
        'end_date': end_date
    }


    return render(request,'studentregister.html',context)
def searchindex(request):
    register=Registers.objects.all()
    context={
        'register_list':register,
             }
    return render(request,'searchindex.html',context)
def detail(request,reg_id):
    register=Registers.objects.get(id=reg_id)
    return render(request,'registerdetail.html',{'register':register})

billproject/templates/base.html
{% load static %}
<html>
<head>
    <title></title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body style="background-color: lightblue;">
<img class="bgimage" src="{% static 'img/regbg.jpg' %}" alt="hg" width="100%" height="45%">

{% block content %}
{% endblock %}
</body>
</html>

billproject/templates/detail.html
<!DOCTYPE html>

<html>

<head>

<title>Receipt</title>

</head>

<body>

<h1>Receipt</h1>

<p>Name: {{ student.name }}</p>

<p>Email: {{ student.email }}</p>

<p>Course: {{ student.course }}</p>

<p>Course Fee: {{ student.course_fee }}</p>

<p>Opening Balance: {{ student.opening_balance }}</p>

</body>

</html>

</body>

</html>

billproject/templates/footer.html
{% extends 'base.html' %}
<div>
    class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
    <!-- Copyright -->
    <div class="text-white mb-3 mb-md-0">
      Copyright © 2020. All rights reserved.
    </div>
    <!-- Copyright -->

    <!-- Right -->
    <div>
      <a href="#!" class="text-white me-4">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="#!" class="text-white me-4">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="#!" class="text-white me-4">
        <i class="fab fa-google"></i>
      </a>
      <a href="#!" class="text-white">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </div>
</div>

billproject/templates/receipt.html
<!DOCTYPE html>

<html>

<head>

<title>Receipt</title>

</head>

<body>

<h1>Receipt</h1>

<p>Name: {{ student.name }}</p>

<p>Email: {{ student.email }}</p>

<p>Course: {{ student.course }}</p>

<p>Course Fee: {{ student.course_fee }}</p>

<p>Opening Balance: {{ student.opening_balance }}</p>
<button onclick="window.print()">Print</button>

</body>

</html>

</body>

</html>

billproject/templates/registerdetail.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid body333" >
    <div class="row">
         <div class="col-md-12">
    <div class="banner">
            <div class="banner-text">
                <h1>Student Details</h1>
            </div></div>
</div></div></div>
<p>Admission Number:{{register.admn_no}}</p>
<p>Student Name:{{register.sname}}</p>
<p>Date Of Birth:{{register.dob}}</p>
<p>Aadhar Number:{{register.aadharno}}</p>
<p>Email id:{{register.email_id}}</p>
<p>Ph No:{{register.phno}}</p>
<p>Address:{{register.address}}</p>
<p>Date Of Joining:{{register.doj}}</p>
<p>Course Duration:{{register.duration}}</p>
<p>Course End Date:{{register.end_date}}</p>
<p>Class Mode:{{register.mode}}</p>
<p>Total Course:{{register.course_fee}}</p>
<p>EMI:{{register.emi}}</p>
<p>Per Month:{{register.permonth}}</p>
{% endblock %}

billproject/templates/searchindex.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid body333" >
    <div class="row">
         <div class="col-md-12">
    <div class="banner">
            <div class="banner-text">
                <h1>Enrolled Student List</h1>
            </div></div>
</div></div></div>

{% for i in register_list %}
<a href="{% url 'credentails:registerdetail' i.id%}">{{i.admn_no}}</a><br>
{% endfor %}
{% endblock %}

billproject/templates/studentregister.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid body333" >
    <div class="row">
         <div class="col-md-12">
    <div class="banner">
            <div class="banner-text">
                <h1>Student Registration Form</h1>
            </div></div>
</div></div></div>

<div class="container">
  <div class="row">
    <div class="col-md-12">

      <form method="post" class="mb3-shadow">
        {% csrf_token %}

        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Admission No:</label>
         <div class="col-sm-10">
<input type="number" class="form-control" name="admn_no"><br>
         </div></div>
        <div class="form-group row">
<label class="col-sm-2 col-form-label">Student Name:</label>
        <div class="col-sm-10">
<input type="text" class="form-control" name="sname">
        </div></div>
   <div class="form-group row">
  <label class="col-sm-2 col-form-label">Dob</label>
     <div class="col-sm-10">
  <input type="date" class="form-control" name="dob">
       </div></div>
     <div class="form-group row">
  <label class="col-sm-2 col-form-label">Aadhar Number</label>
       <div class="col-sm-10">
<input type="number" class="form-control" name="aadharno"><br>
</div></div>
     <div class="form-group row">
<label class="col-sm-2 col-form-label">Email:</label>
<div class="col-sm-10">
<input type="email" class="form-control" name="email_id">
</div></div>
      <div class="form-group row">
  <label class="col-sm-2 col-form-label">Phone Number</label>
<div class="col-sm-10">
<input type="number" class="form-control" name="phno">
  </div></div>
     <div class="form-group row">

  <label class="col-sm-2 col-form-label">Address:</label>
<div class="col-sm-10">
<textarea id="address" class="form-control" rows="5" colos="50" name="address"></textarea>
    </div></div>

<div class="form-group row">

  <label class="col-sm-2 col-form-label">Course Name:</label>
<div class="col-sm-10">
<input type="text" name="course" class="form-control">
   </div></div>
     <div class="form-group row">
  <label class="col-sm-2 col-form-label">Date Of Joining:</label>
     <div class="col-sm-10">
       <input type="date" name="doj" class="form-control">
     </div></div>
      <div class="form-group row">
  <label class="col-sm-2 col-form-label">Course Duration(in months):</label>
         <div class="col-sm-10">
  <input type="number" name="duration" class="form-control">
          </div></div>
<!--
 <label for="end_date">End date:</label>
  <input type="date" id="end_date" name="end_date" value="{{ end_date }}" readonly>
  <br>-->

        <div class="form-group row">
  <label class="col-sm-2 col-form-label">Mode Of Learning:</label>
     <div class="col-sm-10">
<select id="mode" name="mode" class="form-control">
  <option value="online">Online</option>
  <option value="offline">Offline</option>
  <option value="recorded">Recorded</option>

</select>
     </div></div>
   <div class="form-group row">

<label class="col-sm-2 col-form-label">Course Fee:</label>
 <div class="col-sm-10">
<input type="number" name="course_fee" class="form-control">
     </div></div>
     <div class="form-group row">

  <label class="col-sm-2 col-form-label">Course Emi:</label>

<div class="col-sm-10">
<input type="number" name="emi" class="form-control"><br>
</div></div>
          <div class="form-group row">
<!--
<label class="col-sm-2 col-form-label">Per Month:</label>
 <div class="col-sm-10">
<input type="number" name="permonth" value="{{ permonth }}" readonly class="form-control">
     </div></div>-->
          <div class="btn-container">
         <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-success">Register</button>
    </div>
  </div></div>
        </form>
    </div>
  </div>
</div>

{% endblock %}

billproject/templates/studreg.html
<!DOCTYPE html>

<html>

<head>

<title>Student Form</title>

</head>

<body>

<h1>Student Form</h1>

<form method="post">

{% csrf_token %}
    <label>Admission No:</label>

<input type="text" name="admn_no"><br>


<label>Course Fee:</label>

<input type="number" name="course_fee"><br>
<label>Opening Balance:</label>

<input type="number" name="opening_balance"><br>


<br>

<input type="submit" value="Submit">

</form>

</body>

</html>